## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := x86_64-win64-vs16
ALL_TARGETS += libs
ALL_TARGETS += examples
ALL_TARGETS += tools
ALL_TARGETS += docs
ALL_TARGETS += solution

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nodocs-x86_64-win64md-vs16-v1.9.0-122-gebac57ce9
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.9.0-122-gebac57ce9

VERSION_MAJOR=1
VERSION_MINOR=9
VERSION_PATCH=0

CONFIGURE_ARGS=--target=x86_64-win64-vs16 --as=auto --enable-vp9-highbitdepth --enable-vp8 --enable-vp9 --enable-error-concealment --enable-runtime-cpu-detect --enable-libyuv
CONFIGURE_ARGS?=--target=x86_64-win64-vs16 --as=auto --enable-vp9-highbitdepth --enable-vp8 --enable-vp9 --enable-error-concealment --enable-runtime-cpu-detect --enable-libyuv
